using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PauseMenu : MonoBehaviour
{

	public static bool GameIsPaused = false;
	public GameObject pausedUI;

	// Update is called once per frame
	void Update()
	{
		if (Input.GetKeyDown(KeyCode.Escape))
		{
			if (GameIsPaused)
			{
				Resume();
			}
			else
			{
				Pause();
			}
		}
	}
	public void Resume()
	{
		pausedUI.SetActive(false);
		Time.timeScale = 1f;
		GameIsPaused = false;
	}
	public void Pause()
	{
		pausedUI.SetActive(true);
		Time.timeScale = 0f;
		GameIsPaused = true;
	}
	public void MenuExit()
	{
		SceneManager.LoadScene("main-menu");
	}
	public void Exit()
	{
		Application.Quit();
	}

}
